package com.ecommerce.enums;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    ORDER_DELIVERED,
    PRODUCT_CREATED,
    STOCK_LOW_ALERT,
    STOCK_OUT_ALERT,
    STOCK_RESTOCKED,
    ACCOUNT_ACTIVATION_LINK,
    ACCOUNT_ACTIVATED,
    PASSWORD_RESET_LINK,
    PASSWORD_RESET_CONFIRMED
}
